# Generated by Django 4.0.6 on 2022-07-22 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoapp',
            old_name='description',
            new_name='todo',
        ),
        migrations.RemoveField(
            model_name='todoapp',
            name='title',
        ),
    ]
