# Generated by Django 4.0.6 on 2022-07-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_description_todoapp_todo_remove_todoapp_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoapp',
            name='todo',
            field=models.CharField(max_length=500),
        ),
    ]
